controllers/edit_account.py
#! /usr/bin/python
# -*- coding:utf-8 -*-

from flask import Blueprint
from flask import Flask, request, render_template, redirect, flash, session
from werkzeug.security import generate_password_hash, check_password_hash

from connection_bdd import get_db
from controllers.admin_session import admin_session
from controllers.player_session import player_session
from controllers.visitor_session import visitor_session
import io
from flask import Blueprint
from flask import Flask, render_template, request, redirect, url_for, send_file
from werkzeug.utils import secure_filename

from connection_bdd import get_db
from controllers.admin_session import admin_session


edit_account = Blueprint('edit_account', __name__,
                         template_folder = 'templates')


@edit_account.route('/editaccount', methods = ['GET'])
def editaccount():
    if session['fonction'] == 'ADMIN':
        return redirect('/editaccount/admin')
    elif session['fonction'] == 'PLAYER':
        return redirect('/editaccount/player')
    else:
        return redirect('/editaccount/visitor')


@edit_account.route('/editaccount/player', methods = ['POST'])
def valid_player_account():
    mycursor = get_db().cursor()
    id = request.form.get('id')
    pseudo = request.form.get('pseudo', '')
    email = request.form.get('email', '')
    mdp = request.form.get('mdp', '')
    file = request.files['file']
    if file:
        print("img")
        imageBlob = file.read()
        print(imageBlob)
    else:
        print("no img")
        imageBlob = None

    mdp = generate_password_hash(mdp, method = 'pbkdf2:sha256')
    values = (pseudo, email, mdp, imageBlob, id,)
    sql = '''UPDATE utilisateur u
    JOIN joueurs j ON u.idJoueur = j.idJoueur
    set pseudo=%s,email=%s,mdp=%s,u.imgProfile=%s WHERE u.idJoueur=%s'''
    mycursor.execute(sql, values)
    get_db().commit()
    return redirect('/player/index')

###############################

@edit_account.route('/editaccount/visitor',methods = ['GET'])
def edit_visitor():
    mycursor = get_db().cursor()
    id_user = session['id_user']
    sql_u = '''SELECT * FROM utilisateur u WHERE u.idUtilisateur =%s;'''
    mycursor.execute(sql_u, (id_user,))
    visitor = mycursor.fetchone()
    visitorsession = visitor_session()
    get_db().commit()
    return render_template('visitor/visitor_profile.html',visitor=visitor,visitorsession=visitorsession)

@edit_account.route('/editaccount/player',methods = ['GET'])
def edit_player():
    mycursor = get_db().cursor()
    id_user = session['id_player']
    sql_u = '''SELECT * FROM utilisateur u 
    join joueurs j on u.idJoueur = j.idJoueur
    WHERE u.idUtilisateur =%s;'''
    mycursor.execute(sql_u, (id_user,))
    player = mycursor.fetchone()
    playersession = player_session()
    get_db().commit()
    return render_template('player/player_profile.html',player=player,playersession=playersession)

@edit_account.route('/editaccount/admin',methods = ['GET'])
def edit_admin():
    mycursor = get_db().cursor()
    id_user = session['id_admin']
    sql_u = '''SELECT * FROM utilisateur u 
    join `bdd-player`.admin a on u.idAdmin = a.idAdmin
    WHERE u.idUtilisateur =%s;'''
    mycursor.execute(sql_u, (id_user,))
    admin = mycursor.fetchone()
    adminsession = admin_session()
    get_db().commit()
    return render_template('admin/admin_profile.html',admin=admin,adminsession=adminsession)


######################################################

@edit_account.route('/images/<int:id>')
def image(id):
    mycursor = get_db().cursor()
    mycursor.execute("SELECT imgProfile FROM utilisateur WHERE idUtilisateur = %s", (id,))
    image_data = mycursor.fetchone()


    if image_data:
        image_blob = image_data['imgProfile']
        return send_file(io.BytesIO(image_blob), mimetype='image/jpeg')
    else:
        return "Image not found", 404

controllers/player_compo.py
#! /usr/bin/python
# -*- coding:utf-8 -*-

from flask import Blueprint
from flask import Flask, request, render_template, redirect, flash, session
from werkzeug.security import generate_password_hash, check_password_hash

from connection_bdd import get_db
from controllers.admin_map_agent import pyfetchMap, pyfetchAgent
from controllers.player_session import player_session

player_compo = Blueprint('player_compo', __name__,
                         template_folder = 'templates')


@player_compo.route('/compo_show')
def player_compo_show():
    mycursor = get_db().cursor()
    try:
        get_db().begin()

        sql_joueurs = '''SELECT * FROM joueurs 
                         JOIN role r ON joueurs.idRole = r.idRole
                         LIMIT 5 ;'''
        mycursor.execute(sql_joueurs)
        titulaire = mycursor.fetchall()

        sql_map = '''SELECT * FROM map ORDER BY libelle ASC;'''
        mycursor.execute(sql_map)
        maps = mycursor.fetchall()

        if not maps:
            pyfetchMap()
            mycursor.execute(sql_map)
            maps = mycursor.fetchall()

        sql_agent = '''SELECT * FROM agent WHERE nomAgent NOT LIKE 'None' ORDER BY nomAgent ASC;'''
        mycursor.execute(sql_agent)
        agents = mycursor.fetchall()

        if not agents:
            pyfetchAgent()
            mycursor.execute(sql_agent)
            agents = mycursor.fetchall()

        selected_map_id = [item['idMap'] for item in maps]
        selected_joueur_id = [item['idJoueur'] for item in titulaire]
        selected_agent_id = [item['idAgent'] for item in agents]

        sql_compo = '''SELECT j.pseudo, m.libelle, a.nomAgent, j.idJoueur, m.idMap, a.idAgent, a.imgAgent 
                       FROM compo 
                       JOIN agent a ON compo.idAgent = a.idAgent
                       JOIN map m ON compo.idMap = m.idMap
                       JOIN joueurs j ON compo.idJoueur = j.idJoueur
                       WHERE compo.idMap IN %s AND compo.idJoueur IN %s AND compo.idAgent IN %s;'''

        mycursor.execute(sql_compo, (tuple(selected_map_id), tuple(selected_joueur_id), tuple(selected_agent_id)))
        compo = mycursor.fetchall()

        sql_delete = '''DELETE FROM compo WHERE idAgent=1'''
        mycursor.execute(sql_delete)

        sql_roles = '''SELECT * FROM role;'''
        mycursor.execute(sql_roles)
        roles = mycursor.fetchall()

        playersession = player_session()

        get_db().commit()
    except Exception as e:
        get_db().rollback()
        flash(f"Erreur lors de l'affichage des compositions : {e}", 'error')
        return redirect('/error_page')

    return render_template('player/player_compo.html', titulaire=titulaire, maps=maps, agents=agents,
                           compo=compo, playersession=playersession, roles=roles)



@player_compo.route('/compo_edit', methods = ['POST'])
def player_compo_edit():
    mycursor = get_db().cursor()
    try:
        get_db().begin()
        id_player = request.form.get('Joueurs', '')
        id_map = request.form.get('Map', '')
        id_agent = request.form.get('Agent', '')

        sql_select = '''SELECT * FROM compo 
                        JOIN agent a ON compo.idAgent = a.idAgent
                        JOIN map m ON compo.idMap = m.idMap
                        JOIN joueurs j ON compo.idJoueur = j.idJoueur
                        WHERE compo.idJoueur=%s AND compo.idMap=%s;'''
        mycursor.execute(sql_select, (id_player, id_map,))
        pick = mycursor.fetchone()

        if pick:
            sql_update = '''UPDATE compo SET compo.idAgent = %s 
                            WHERE compo.idJoueur=%s AND compo.idMap=%s;'''
            mycursor.execute(sql_update, (id_agent, id_player, id_map,))
        else:
            sql_insert = '''INSERT INTO compo (idJoueur, idMap, idAgent) 
                            VALUES (%s, %s, %s);'''
            mycursor.execute(sql_insert, (id_player, id_map, id_agent,))

        get_db().commit()
    except Exception as e:
        get_db().rollback()
        flash(f"Erreur lors de la modification de la composition : {e}", 'error')
    return redirect('/compo_show')


@player_compo.route('/delete_column/<id_player>', methods = ['GET'])
def player_compo_delete_column(id_player):
    mycursor = get_db().cursor()
    sql = '''DELETE FROM compo WHERE compo.idJoueur=%s;'''
    mycursor.execute(sql,(id_player,))
    get_db().commit()
    return redirect('/compo_show')

@player_compo.route('/delete_row/<id_map>', methods = ['GET'])
def player_compo_delete_row(id_map):
    mycursor = get_db().cursor()
    sql = '''DELETE FROM compo WHERE compo.idMap=%s;'''
    mycursor.execute(sql, (id_map,))
    get_db().commit()
    return redirect('/compo_show')

controllers/player_horaire.py
#! /usr/bin/python
# -*- coding:utf-8 -*-

from flask import Blueprint
from flask import Flask, request, render_template, redirect, flash, session
from werkzeug.security import generate_password_hash, check_password_hash

from connection_bdd import get_db
from controllers.player_session import player_session

player_horaire = Blueprint('player_horaire', __name__,
                           template_folder = 'templates')


@player_horaire.route('/horaire/show')
def player_horaire_show():
    mycursor = get_db().cursor()
    id_user = session['id_user']

    sql_jour = '''SELECT * FROM jour;'''
    mycursor.execute(sql_jour)
    jours = mycursor.fetchall()
    sql_heure = '''SELECT * FROM heure;'''
    mycursor.execute(sql_heure)
    heures = mycursor.fetchall()

    sql_horaire = '''SELECT * FROM horaire where idJoueur =%s;'''
    mycursor.execute(sql_horaire, (id_user,))
    horaires = mycursor.fetchall()

    sql_player = '''SELECT * FROM joueurs where titulaire=1;'''
    mycursor.execute(sql_player)
    players = mycursor.fetchall()

    playersession = player_session()
    return render_template('player/player_horaire.html',
                           playersession = playersession,
                           jours = jours,
                           heures = heures,
                           horaires = horaires,
                           players = players)


@player_horaire.route('/horaire/fetch', methods=['POST'])
def player_horaire_fetch():
    mycursor = get_db().cursor()
    id_user = session['id_user']
    data = request.json

    try:
        get_db().begin()

        sql_select_all = '''SELECT * FROM horaire WHERE idJoueur=%s;'''
        mycursor.execute(sql_select_all, (id_user,))
        allHoraire = mycursor.fetchall()

        for horaire in allHoraire:
            heure = int(horaire['idHeure'])
            jour = int(horaire['idJour'])
            frontend_exists = False

            for itemdata in data:
                col = int(itemdata['col'])
                row = int(itemdata['row'])
                if row == heure and col == jour:
                    frontend_exists = True
                    break

            if not frontend_exists:
                sql_delete = '''DELETE FROM horaire WHERE idJoueur=%s AND idHeure=%s AND idJour=%s;'''
                mycursor.execute(sql_delete, (id_user, heure, jour))

        for itemdata in data:
            col = int(itemdata['col'])
            row = int(itemdata['row'])
            bdd_exists = False

            for horaire in allHoraire:
                heure = int(horaire['idHeure'])
                jour = int(horaire['idJour'])
                if row == heure and col == jour:
                    bdd_exists = True
                    break

            if not bdd_exists:
                sql_insert = '''INSERT INTO horaire (idJoueur, idHeure, idJour) VALUES (%s, %s, %s);'''
                mycursor.execute(sql_insert, (id_user, row, col))

        get_db().commit()
    except Exception as e:
        get_db().rollback()
        flash(f"Erreur lors de la mise à jour des horaires : {e}", 'error')
        return redirect('/error_page')

    return redirect('/horaire/show')



@player_horaire.route('/horaire/reset', methods = ['POST'])
def player_horaire_reset():
    mycursor = get_db().cursor()
    id_user = session['id_user']
    sql_delete = '''DELETE FROM horaire where idJoueur=%s;'''
    mycursor.execute(sql_delete, (id_user,))
    return redirect('/horaire/show')

controllers/player_roaster.py
#! /usr/bin/python
# -*- coding:utf-8 -*-

from flask import Blueprint
from flask import Flask, request, render_template, redirect, flash, session
from werkzeug.security import generate_password_hash, check_password_hash

from connection_bdd import get_db
from controllers.player_session import player_session

player_roaster = Blueprint('player_roaster', __name__,
                           template_folder = 'templates')


@player_roaster.route('/roaster_show')
def player_roaster_show():
    mycursor = get_db().cursor()




    sql = '''SELECT * FROM utilisateur u
    join joueurs j on u.idJoueur = j.idJoueur
    join role r on j.idRole = r.idRole;'''
    mycursor.execute(sql)
    players = mycursor.fetchall()
    nbr_joueurs = len(players)
    print('roaster :',players)

    sql = '''SELECT * FROM utilisateur u
        join joueurs j on u.idJoueur = j.idJoueur
        join role r on j.idRole = r.idRole where j.titulaire=1;'''
    mycursor.execute(sql)
    roaster = mycursor.fetchall()
    nbr_titu = len(roaster)
    print('roaster :', roaster)

    # connecté en tant que
    id_user = session['id_user']
    sql_ps = '''SELECT * FROM utilisateur u 
            join joueurs j on u.idJoueur = j.idJoueur
            where u.idJoueur=%s;'''
    mycursor.execute(sql_ps, (id_user,))
    playersession = mycursor.fetchone()

    get_db().commit()
    return render_template('player/player_roaster.html',
                           players = players,
                           roaster = roaster,
                           nbr_titu = nbr_titu,
                           nbr_joueurs = nbr_joueurs,
                           playersession = playersession)



templates/player/index.html
{% include 'player/player_layout.html' %}
<body>
<main>
    <h1>Bienvenue {{player.pseudo}}</h1>
    <div class="player-index-containers">
        <div>
            <img src="https://valorantinfo.com/images/fr/neon_valorant_icon_3709.webp" style="aspect-ratio: auto; width: 300px">
        </div>


        <table style="margin: 0;">
            <thead>
            <th colspan="30">Derniers Match</th>
            </thead>

            <tbody>

            {% for item in matchs %}
                <tr>
                    <td>{{item.nomMatch}}</td>
                    <td>{{item.date_match}}</td>
                    {% if item.lien ==None %}
                        <td> X </td>
                    {% else %}
                        <td><a href="{{item.lien}}" style="text-decoration: none;color: var(--black);"><i class="fa-regular fa-circle-play fa-xl" style="color: #000000;"></i></a></td>
                    {% endif %}
                </tr>

            {% endfor %}

            </tbody>
        </table>
        <article class="article-player-index">
            <h2>Patch Notes : X</h2>
            <ul>
                {% if patch | length >= 1 %}
                    {% for item in patch %}
                        <li>{{item.contenu}}</li>

                    {% endfor %}

                {% else %}
                        <li>Aucun Patch Récent ...</li>
                {% endif %}
            </ul>
        </article>
        <article class="article-player-index">
            <h2>Nouveautés du Serveur Discord</h2>
            <ul>
                {% if discord | length >= 1 %}
                    {% for item in discord %}
                        <li>{{item.contenu}}</li>

                    {% endfor %}

                {% else %}

                    <li>Aucune Nouveauté sur le serveur ...</li>
                {% endif %}
            </ul>
        </article>

    </div>


</main>
</body>
{% include 'layout/footer.html' %}

templates/player/player_adddir.html
{% include 'player/player_layout.html' %}
<body>
<main>
<form action="/dir/add" method="post">
    <fieldset class="directory-add">
        <input type="hidden" value="{{map}}" name="idmap">

        <div>
        <label for="name"> Nom</label>
        <input type="text" name="name" id="name">
        </div>
        <div>
        <label for="description"> Description</label>
        <textarea id="description" name="description" style="width: 65%"></textarea>
        </div>
        <div class="addfile" style="display: none">
            <input type="file" name="" id="">
        </div>
        <a onclick="addFile()">Ajouter un plan</a>
        <button type="submit">Créer</button>
    </fieldset>
</form>
</main>
<script>
    function addFile() {
    const div = document.createElement('div');

    const nameLabel = document.createElement('label');
    nameLabel.setAttribute('for', 'name');
    nameLabel.textContent = 'Name:';

    const name = document.createElement('input');
    name.setAttribute('id', 'name');
    name.setAttribute('name', 'name');
    name.setAttribute('type', 'text'); // Si 'name' est un champ texte

    const descLabel = document.createElement('label');
    descLabel.setAttribute('for', 'description');
    descLabel.textContent = 'Description:';

    const desc = document.createElement('input');
    desc.setAttribute('id', 'description');
    desc.setAttribute('name', 'description');
    desc.setAttribute('type', 'text'); // Si 'description' est un champ texte

    const fileLabel = document.createElement('label');
    fileLabel.setAttribute('for', 'file');
    fileLabel.textContent = 'File:';

    const file = document.createElement('input');
    file.setAttribute('id', 'file');
    file.setAttribute('name', 'file');
    file.setAttribute('type', 'file'); // Spécifiez le type 'file' pour l'input de fichier

    div.appendChild(nameLabel);
    div.appendChild(name);
    div.appendChild(descLabel);
    div.appendChild(desc);
    div.appendChild(fileLabel);
    div.appendChild(file);

    // Ciblez le form et le fieldset corrects
    const form = document.querySelector('form'); // Ciblez le formulaire par sa balise (vous pouvez ajouter un id ou une classe spécifique pour plus de précision)
    const fieldset = form.querySelector('fieldset'); // Ciblez le fieldset dans ce formulaire

    // Ajoutez le div dans le fieldset
    fieldset.appendChild(div);
}



</script>
</body>
{% include 'layout/footer.html' %}

templates/player/player_compo.html
{% include 'player/player_layout.html' %}
<body onload="selectByRole()">
<main class="player-compo">
    <table>

        <caption>
            Tableau des Compo
        </caption>

        <thead>
        <tr>
            <th></th>
            {% for ligne in titulaire %}
            <th scope="col">{{ligne.pseudo}}</th>
            {% endfor %}
        </tr>
        </thead>

        <tbody>
        {% for map in maps %}
        <tr>
            <th>{{ map.libelle }}</th>
            {% for joueur in titulaire %}

            <td class="compo-td">

                {% for compo_entry in compo %}
                {% if map.idMap == compo_entry.idMap and joueur.idJoueur == compo_entry.idJoueur and compo_entry.nomAgent != 'None' %}
<!--                {{ compo_entry.nomAgent }}-->
                <img src="https://media.valorant-api.com/agents/{{ compo_entry.imgAgent }}" alt="" class="img-compo-player">
                {% endif %}


                {% endfor %}


            </td>

            {% endfor %}
            <td><a href="/delete_row/{{map.idMap}}" class="delete"><i class="fa-solid fa-trash fa-flip-horizontal fa-xl"
                                                                      style="color: #000000;"></i></a></td>

        </tr>
        {% endfor %}


        </tbody>

        <tfoot>
        <tr>
            <th></th>
            <th scope="row">Duelliste</th>
            <th scope="row">Initiateur</th>
            <th scope="row">Flex</th>
            <th scope="row">Controlleur</th>
            <th scope="row">Sentinelle</th>
        </tr>
        <tr>
            <th></th>
            {% for joueur in titulaire %}
            <th scope="row"><a href="/delete_column/{{joueur.idJoueur}}" class="delete"><i
                    class="fa-solid fa-trash fa-flip-horizontal fa-xl" style="color: #000000;"></i></a></th>
            {% endfor %}

        </tr>
        </tfoot>
    </table>


    <form method="POST" action="/compo_edit" class="form-edit-compo">
        <fieldset>

            <div>
                <label for="Map">Map :</label>
                <select name="Map" id="Map" required>
                    <option value="" selected>-- Map --</option>
                    {% for ligne in maps %}
                    <option value="{{ligne.idMap}}">{{ligne.libelle}}</option>
                    {% endfor %}
                </select>
            </div>
            <div>
                <label for="Joueurs">Joueur :</label>
                <select name="Joueurs" id="Joueurs" onchange="selectByRole()" required>
                    <option value="" id="not" selected>-- Joueur --</option>
                    {% for ligne in titulaire %}
                    <option value="{{ligne.idJoueur}}" id="{{ligne.libelle}}">{{ligne.pseudo}}</option>
                    {% endfor %}
                </select>
            </div>
            <div>
                <label for="Agent">Agent :</label>
                <select name="Agent" id="Agent" required>
                    <option value="" >-- Agent --</option>
                    <option value="1" id="" >None</option>
                    {% for ligne in agents %}
                    <option value="{{ligne.idAgent}}" id="{{ligne.roleAgent}}" >{{ligne.nomAgent}}
                    </option>
                    {% endfor %}
                </select>
            </div>



            <button type="submit" name="submitedit" class="submit-edit-compo">MODIFIER</button>
        </fieldset>

    </form>


</main>

<script>
    function selectByRole() {
    const selectedOption = document.getElementById("Joueurs").options[document.getElementById("Joueurs").selectedIndex];
    const Aoptions = document.querySelectorAll('#Agent option');

    if (selectedOption.id !== 'not'){
        Aoptions.forEach(option => {
        if (option.id !== ''){
            option.style.display = (selectedOption.id === option.id || selectedOption.id === 'Flex') ? '' : 'none';
        }
    });
    } else {
        Aoptions.forEach(option => {
            option.style.display = (option.id !== '') ? 'none': '';
        });
    }



}




</script>
</body>
{% include 'layout/footer.html' %}

templates/player/player_layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>DESTROY - Accueil </title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
        integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="
        crossorigin="anonymous" referrerpolicy="no-referrer">
    <link rel="shortcut icon" href="{{ url_for('static', filename='assets/icones/favicon.ico') }}" >
    {% block stylesheets %}
        <link rel="stylesheet" href="{{ url_for('static', filename='src/css/bootstrap.css') }}" >
        <link rel="stylesheet" href="{{ url_for('static', filename='src/css/style.css') }}" >
    {% endblock %}
</head>
<body>
{% include 'player/player_nav.html' %}

</body>
</html>

templates/player/player_nav.html
<nav>
    <div class="nav-left">

        <a href="/player/index"><i class="fa-solid fa-house" style="color: #000000;"></i></a>
        <a href="/roaster_show"><i class="fa-solid fa-users" style="color: #000000;"></i></a>
        <a href="/horaire/show"><i class="fa-solid fa-clock" style="color: #000000;"></i></a>
        <a href="/compo_show"><i class="fa-solid fa-users-viewfinder" style="color: #000000;"></i></a>
        <a href="/strats_show"><i class="fa-solid fa-chess-pawn" style="color: #000000;"></i></a>
    </div>
    <h2>DESTROY ACADEMY</h2>
    <div class="nav-right">

        <div class="display-log">

                {% if playersession.imgProfile == None %}
                        <i class="fa-solid fa-circle-user fa-2xl" style="color: #000000;"></i>
<!--                    <img src="{{ url_for('static', filename='assets/img/no_img.jpg') }}" alt="">-->
                {% else %}
                        <img src="{{ url_for('edit_account.image', id=playersession.idJoueur) }}" class="photo-profil">

                {% endif %}
                <em>Compte :  </em>
                <b class="b-player"><i class="fa-solid fa-gamepad fa-beat" ></i> {{playersession.pseudo}} </b>


        </div>
        <a href="/editaccount"><i class="fa-solid fa-user-pen" style="color: #000000;"></i></a>
        <a href="/logout"><i class="fa-solid fa-right-to-bracket" style="color: #000000;"></i></a>

    </div>
</nav>
<input type="hidden" value="{{playersession.idUtilisateur}}">

templates/player/player_roaster.html
{% include 'player/player_layout.html' %}
<body>
<div class="roaster-body">
    <table class="all-player">

        <caption>
            Tableau de tous les joueurs de DESTROY ACADEMY
        </caption>

        <thead>
        <tr>
            <th scope="col">Profil</th>
            <th scope="col">Pseudo</th>
            <th scope="col">Role</th>

            <th scope="col">Connecté</th>
        </tr>
        </thead>

        <tbody>

        {% if players | length >= 1 %}
        {% for ligne in players %}

        <tr>
            <td>{% if ligne.imgProfile == None %}
                        <i class="fa-solid fa-circle-user fa-2xl" style="color: #000000;"></i>
<!--                    <img src="{{ url_for('static', filename='assets/img/no_img.jpg') }}" alt="">-->
                {% else %}
                        <img src="{{ url_for('edit_account.image', id=ligne.idJoueur) }}" style="max-width: 50px; height: auto; aspect-ratio:1/1;border-radius:150px ">

                {% endif %}</td>
            <td>{{ ligne.pseudo }}</td>
            <td>{{ ligne.libelle }}</td>
            <td>
                {% if ligne.connected == 1 %}
                    {% set etat = 'ONLINE' %}
                    <b class="online">{{etat}}</b>
                {% else %}
                    {% set etat = 'OFFLINE' %}
                    <em class="offline"><b>{{etat}}</b></em>
                {% endif %}

            </td>
        </tr>

        {% endfor %}
        {% else %}
        <tr>
            <td>
                pas de joueurs :C
            </td>
        </tr>
        {% endif %}


        </tbody>

        <tfoot>
        <tr>
            <th scope="row" colspan="3">Nombre de Joueurs</th>
            <td>{{nbr_joueurs}}</td>
        </tr>
        </tfoot>
    </table>

    <table class="titulaire">

        <caption>
            Tableau des Titulaires de DESTROY ACADEMY
        </caption>

        <thead>
        <tr>
            <th scope="col">Profil</th>
            <th scope="col">Pseudo</th>
            <th scope="col">Role</th>
            <th scope="col">Connecté</th>
        </tr>
        </thead>

        <tbody>

        {% if roaster | length >= 1 %}
        {% for ligne in roaster %}
        {% if ligne.titulaire == true %}
        <tr>
            <td>{% if ligne.imgProfile == None %}
                        <i class="fa-solid fa-circle-user fa-2xl" style="color: #000000;"></i>
<!--                    <img src="{{ url_for('static', filename='assets/img/no_img.jpg') }}" alt="">-->
                {% else %}
                        <img src="{{ url_for('edit_account.image', id=ligne.idJoueur) }}" style="max-width: 50px; height: auto; aspect-ratio:1/1;border-radius:150px ">

                {% endif %}</td>
            <td>{{ ligne.pseudo }}</td>
            <td>{{ ligne.libelle }}</td>

            <td>
                {% if ligne.connected == 1 %}
                    {% set etat = 'ONLINE' %}
                    <b class="online">{{etat}}</b>
                {% else %}
                    {% set etat = 'OFFLINE' %}
                    <em class="offline"><b>{{etat}}</b></em>
                {% endif %}

            </td>
        </tr>
        {% endif %}
        {% endfor %}
        {% else %}
        <tr>
            <td>
                pas de joueurs :C
            </td>
        </tr>
        {% endif %}


        </tbody>

        <tfoot>
        <tr>
            <th scope="row" colspan="3">Nombre de Joueurs</th>
            <td>{{nbr_titu}}</td>
        </tr>
        </tfoot>
    </table>
</div>
</body>
{% include 'layout/footer.html' %}

templates/player/show_dir.html
{% include 'player/player_layout.html' %}
<h1> Dossier {{name.nomDossier}}</h1>

{% for item in dir %}
    <div>
        <img src="" alt="Plan">
    </div>
{% endfor %}
{% include 'layout/footer.html' %}